version: "1.0"

services:
  app:
    build:
      context: .
    container_name: telegram_bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "python telbot.py"
    depends_on:
        - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    environment:
        - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http app:5000
